# Generated by Django 4.2.10 on 2024-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='enter_the_amount_to_be_transferred_in_INR',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account_number',
            field=models.IntegerField(),
        ),
    ]
