# Generated by Django 4.2.10 on 2024-02-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_transaction_date_and_time'),
    ]

    operations = [
    ]
