# Generated by Django 4.2.10 on 2024-02-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20240225_2304'),
    ]

    operations = [
    ]
