# Generated by Django 4.2.10 on 2024-02-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20240225_2307'),
    ]

    operations = [
    ]
