# Generated by Django 4.2.10 on 2024-02-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20240225_2316'),
    ]

    operations = [
    ]
