# Generated by Django 4.2.10 on 2024-02-25 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20240225_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
